# Generated by Django 3.1.1 on 2020-09-29 16:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=datetime.date(2020, 9, 29), null=True, verbose_name='Fecha de Historia')),
                ('hora', models.TimeField(default=datetime.time(11, 20, 20, 551167), verbose_name='Hora')),
                ('historiaNo', models.CharField(max_length=50, verbose_name='Numero de Historia')),
                ('notasinterna', models.TextField(verbose_name='Notas Internas')),
                ('estado', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appbase.paciente')),
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Historia Clinicas',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=datetime.date(2020, 9, 29), null=True, verbose_name='Fecha de Atencion')),
                ('hora', models.TimeField(default=datetime.time(11, 20, 20, 535542), verbose_name='Hora')),
                ('motivo', models.CharField(max_length=50, verbose_name='Motivo de Consulta')),
                ('exploracion', models.TextField(verbose_name='Exploracion Fisica')),
                ('instrucciones', models.TextField(verbose_name='Instrucciones Medicas')),
                ('estado', models.BooleanField(default=True)),
                ('diagnostico', models.ManyToManyField(to='appbase.Diagnostico')),
                ('gabinete', models.ManyToManyField(to='appbase.EstudioGabinete')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appbase.paciente')),
                ('sintoma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appbase.sintoma')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='TomarSignoVital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appconsulta.receta')),
                ('signovital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appbase.signovital')),
            ],
            options={
                'verbose_name': 'Tomar Signo Vital',
                'verbose_name_plural': 'Tomar Signo Vitales',
            },
        ),
        migrations.CreateModel(
            name='HistoriaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Antecedente')),
                ('GrupoAntecedente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appbase.grupoantecedente')),
                ('antecedente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appbase.antecedente')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appconsulta.historia')),
            ],
            options={
                'verbose_name': 'Detalle de la Historia Clinica',
                'verbose_name_plural': 'Detalle de las Historias Clinicas',
            },
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appbase.dosis')),
                ('duracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appbase.duracion')),
                ('frecuencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appbase.frecuencia')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appbase.medicamento')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appconsulta.receta')),
            ],
            options={
                'verbose_name': 'DetalleReceta',
                'verbose_name_plural': 'DetalleRecetas',
            },
        ),
    ]
