# Generated by Django 3.1.1 on 2020-09-29 16:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Codigo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Diagnostico')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Diagnostico',
                'verbose_name_plural': 'Diagnosticos',
            },
        ),
        migrations.CreateModel(
            name='Dosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Dosis')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dosis',
                'verbose_name_plural': 'Dosis',
            },
        ),
        migrations.CreateModel(
            name='Duracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Duracion')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Duracion',
                'verbose_name_plural': 'Frecuencias',
            },
        ),
        migrations.CreateModel(
            name='EstudioGabinete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Estudio de gabinete')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estudio de Gabinete',
                'verbose_name_plural': 'Estudio de Gabinete',
            },
        ),
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Frecuencia')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Frecuencia',
                'verbose_name_plural': 'Frecuencias',
            },
        ),
        migrations.CreateModel(
            name='GrupoAntecedente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Grupo de Antecedente')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo de Antecedente',
                'verbose_name_plural': 'Grupo de Antecedentes',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado')], default=1, verbose_name='Dia')),
                ('desde', models.TimeField(blank=True, default='00:00', null=True, verbose_name='Desde')),
                ('hasta', models.TimeField(blank=True, default='00:00', null=True, verbose_name='Hasta')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Medicamento')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='medicamentos/', verbose_name='Foto')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profesion',
                'verbose_name_plural': 'Profesiones',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Sangre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, unique=True, verbose_name='Tipo de Sangre')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Sangre',
                'verbose_name_plural': 'Tipos de Sangre',
            },
        ),
        migrations.CreateModel(
            name='SignoVital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Signo')),
                ('rango1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rango2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medida', models.CharField(max_length=10, verbose_name='Medida')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='signovital/', verbose_name='imagen')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Signo Vital',
                'verbose_name_plural': 'Signo Vitales',
            },
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Sintoma')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sintoma',
                'verbose_name_plural': 'Sintomas',
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Titulo',
                'verbose_name_plural': 'Titulos',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=13, unique=True, verbose_name='Cedula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('sexo', models.CharField(choices=[('N', 'Ninguno'), ('M', 'Masculino'), ('F', 'Femenino')], default='N', max_length=1, verbose_name='sexo')),
                ('civil', models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viudo'), ('U', 'Union')], default='S', max_length=1, verbose_name='Estado civil')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto')),
                ('hijos', models.IntegerField(default=0, verbose_name='No.hijos')),
                ('estado', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appbase.ciudad')),
                ('profesion', models.ManyToManyField(to='appbase.Profesion')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appbase.provincia')),
                ('sangre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appbase.sangre')),
                ('titulo', models.ManyToManyField(to='appbase.Titulo')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=13, unique=True, verbose_name='Cedula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('sexo', models.CharField(choices=[('N', 'Ninguno'), ('M', 'Masculino'), ('F', 'Femenino')], default='N', max_length=1, verbose_name='sexo')),
                ('civil', models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viudo'), ('U', 'Union')], default='S', max_length=1, verbose_name='Estado civil')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto')),
                ('consultorio', models.CharField(max_length=100, verbose_name='Nombre de Consultorio')),
                ('lugar', models.CharField(max_length=100, verbose_name='Direccion de Consultorio')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('registro', models.CharField(max_length=50, verbose_name='Registro Medico')),
                ('duracion', models.IntegerField(default=30, verbose_name='Duracion de Consulta')),
                ('estado', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appbase.ciudad')),
                ('horario', models.ManyToManyField(to='appbase.Horario')),
                ('profesion', models.ManyToManyField(to='appbase.Profesion')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appbase.provincia')),
                ('titulo', models.ManyToManyField(to='appbase.Titulo')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appbase.provincia'),
        ),
        migrations.CreateModel(
            name='AudiUsuarioTabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=100, verbose_name='Tabla')),
                ('registroid', models.IntegerField(verbose_name='Registro Id')),
                ('accion', models.CharField(choices=[('A', 'A'), ('M', 'M'), ('E', 'E')], max_length=1, verbose_name='Accion')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('estacion', models.CharField(max_length=100, verbose_name='Estacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria Usuario',
                'verbose_name_plural': 'Auditorias Usuarios',
                'ordering': ('-fecha', 'hora'),
            },
        ),
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Antecedente')),
                ('estado', models.BooleanField(default=True)),
                ('grupoAntecedente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appbase.grupoantecedente')),
            ],
            options={
                'verbose_name': 'Antecedente',
                'verbose_name_plural': 'Antecedentes',
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=datetime.date(2020, 9, 29), null=True, verbose_name='Fecha de Agenda')),
                ('hora', models.TimeField(default=datetime.time(11, 20, 20, 520054), verbose_name='Hora')),
                ('motivo', models.CharField(max_length=100, verbose_name='Motivo de Consulta')),
                ('estado', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appbase.paciente')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
            },
        ),
    ]
