# Generated by Django 3.1.1 on 2020-09-29 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='hora',
            field=models.TimeField(default=datetime.time(13, 24, 1, 710696), verbose_name='Hora'),
        ),
    ]
